#t
#f
(define maor 5)
(boolean? maor)
(boolean? 5)
(boolean? "#t")
(boolean? #t)
(boolean? #f)
(boolean? 't)
(boolean? 'f)
(define maor #t)
(boolean? maor)
(define maor "maor")
(boolean? maor)
(define maor #f)
(boolean? maor)
(boolean? 'maor)
(boolean? "\x53;")
(boolean? #\a)
(boolean? #\x53)
(boolean? #\newline)
(boolean? "\n")
(boolean? 53/17)
(boolean? '())
(boolean? '(1 2))
(boolean? (and))
(boolean? (or))
(boolean? '#(1 2))

(define booler #t)
(define checker (lambda (x) (lambda (y) (x y))))
((checker boolean?) "string")
((checker boolean?) 'symbol)
((checker boolean?) booler) 
((checker boolean?) #t)
((checker boolean?) 555)
((checker boolean?) 5/7)
((checker boolean?) 3/1)
((checker boolean?) '())
((checker boolean?) '(1 2) )
((checker boolean?) '#(1 2 #t))
((checker boolean?) (begin 1 2 #t))
((checker boolean?) (begin #t 1 2))