#t
#f
(define maor 5)
(not maor)
(not 5)
(not "#t")
(not #t)
(not #f)
(not 't)
(not 'f)
(define maor #t)
(not maor)
(define maor "maor")
(not maor)
(define maor #f)
(not maor)
(not 'maor)
(not "\x53;")
(not #\a)
(not #\x53)
(not #\newline)
(not "\n")
(not 53/17)
(not '())
(not '(1 2))
(not (and))
(not (or))
(not '#(1 2))
(define pnina 7)
(not (not pnina))
(define pnina #t)
(not (not (not pnina)))

(define noter #f)
(define checker (lambda (x) (lambda (y) (x y))))
((checker not) "string")
((checker not) 'symbol)
((checker not) noter) 
((checker not) #t)
((checker not) #f)
((checker not) 555)
((checker not) 5/7)
((checker not) 3/1)
((checker not) '())
((checker not) '(1 2) )
((checker not) '#(1 2 #t))
((checker not) (begin 1 2 #f))
((checker not) (begin #f 1 2))
