#\a
"a"
#\c
"c"

(define maor 'a)
(char? maor)
(char? #\a)
(char? "#t")
(char? #t)
(char? #f)
(char? 't)
(char? 'f)
(define maor #\b)
(char? maor)
(define maor "maor")
(char? maor)
(define maor #f)
(char? maor)
(char? 'maor)
(char? "\x53;")
(char? #\a)
(char? #\A)
(char? #\x53)
(char? #\newline)
(char? #\return)
(char? #\tab)
(char? #\\)
(char? #\page)
(char? "\n")
(char? "\r")
(char? "\f")
(char? "\t")
(char? "\\")
(char? 53/17)
(char? '())
(char? '(1 2))
(char? (and))
(char? (or))
(char? '#(1 2))

(define charer #\x53 )
(define checker (lambda (x) (lambda (y) (x y))))
((checker char?) "string")
((checker char?) 'symbol)
((checker char?) charer) 
((checker char?) #t)
((checker char?) 555)
((checker char?) 5/7)
((checker char?) 3/1)
((checker char?) '())
((checker char?) '(1 2) )
((checker char?) '#(1 2 #t))
((checker char?) (begin 1 2 #\a))
((checker char?) (begin #\b 1 2))