((lambda (x) x) 1)
((lambda (x y) y) 2 3)
((lambda (x y z) z) 0 12 15)
((((lambda (x) (lambda (m) (lambda (z) (begin m x)))) 7 ) 3) 11)
((((lambda (x) (lambda (m) (lambda (z) x))) 7 ) 3 ) 11)
(((lambda (x y z) (lambda (m) z)) 0 1 2)3)
(((((lambda (x) (lambda (y) (lambda (z) (lambda (m) y)))) 2) 3) 1) 4)
((((((lambda (x) (lambda (y) (lambda (z) (lambda (m) (lambda (n) (begin x)))))) 2) 3) 1) 4) 5)
(define foo (lambda (x) (lambda (y) (begin x y))))
((lambda (x) ((lambda (y) (begin x y) ) 7)) 5)
(define koko (lambda (x) (lambda (y) (begin x y) )))
((koko 5) 7)