(vector-length (make-vector 0))
(vector-length (make-vector 0 ))
(vector-length (make-vector 0 0))
(vector-length (make-vector 0 #\a))
(vector-length (make-vector 1))
(vector-length (vector))
(vector? (vector))

(make-vector 5 (vector))
(vector? (make-vector 15 #\a))
(vector-ref (make-vector 3 #\t) 2)
(vector-set! (make-vector 5 #t) 2 #\T)
