(define koko '#(1 -2 5/7 #\a #\x53 #\return #t "\x53;" "\t" "maor"))
koko
(vector-ref '#(1 2 3) 1)
(vector-ref koko 0)
(integer? (vector-ref koko 0))
;; (eq? (vector-ref koko 0) (vector-ref koko 0))
(vector-ref koko 1)
(integer? (vector-ref koko 1)) 
(vector-ref koko 2)
(integer? (vector-ref koko 2))
(number? (vector-ref koko 2))
;; (eq? (vector-ref koko 2) (vector-ref koko 2))
(vector-ref koko 3)
(char? (vector-ref koko 3))
(vector-ref koko 4)
(char? (vector-ref koko 4))
;; (eq? (vector-ref koko 4) (vector-ref koko 4))
(vector-ref koko 5)
(char? (vector-ref koko 5))
(vector-ref koko 6)
(boolean? (vector-ref koko 6))
;; (eq? (vector-ref koko 6) (vector-ref koko 6))
(vector-ref koko 7)
(string? (vector-ref koko 7))
;; (eq? (vector-ref koko 7) (vector-ref koko 7))
(vector-ref koko 8)
(string? (vector-ref koko 8))
;; (eq? (vector-ref koko 8) (vector-ref koko 8))
(vector-ref koko 9)
(string? (vector-ref koko 9))
(vector-ref koko 9)
;; (eq? (vector-ref koko 9) (vector-ref koko 9))

(define checker (lambda (x y) (vector-ref x y)))
(checker koko 1)
;; (eq? (checker koko 3) #\a)
;; (eq? (checker koko 15/5) #\return)
;; (eq? (checker koko 6) #t)
;; (eq? (checker koko 4) #\x53)
;; (eq? (checker koko 2) (checker koko 2))