'#(1 2 3)
'#(1 #t "ff")
(define maor 'a)
(vector? maor)
(vector? '#(1 2 3))
(vector? "#t")
(vector? #t)
(vector? #f)
(vector? 't)
(vector? 'f)
(define maor '#(7 9 4/5 99 "maor" #\b #\newline))
(vector? maor)
(vector? "\x53;")
(vector? #\a)
(vector? #\x53)
(vector? #\newline)
(vector? "\n")
(vector? "\r")
(vector? "\f")
(vector? "\t")
(vector? 53/17)
(vector? '())
(vector? '(1 2))
(vector? (and))
(vector? (or))
(vector? '#(1 2 #t))

(define vectorer 'vector)
(define checker (lambda (x) (lambda (y) (x y))))
((checker vector?) "string")
((checker vector?) 'symbol)
((checker vector?) vectorer) 
((checker vector?) #t)
((checker vector?) 555)
((checker vector?) 5/7)
((checker vector?) 3/1)
((checker vector?) '())
((checker vector?) '(1 2) )
((checker vector?) '#(1 2 #t))
((checker vector?) (begin 1 2 '#(1 2)))
((checker vector?) (begin '#(1 2) 1 2))