(define numberer 5)
(define truer #t)
(define charer #\a)
(define charer2 #\x53)
(vector numberer truer charer charer2)
(vector)
(vector 1 2 3)
(vector (begin 1 2 3))

(vector 0 #\a)
(vector 5 #\b)
(vector 30 #\7)
(vector 0 #\a)
(vector 0 0)
(vector 1)
(vector 2)
(vector 0 #\x53)
(vector 3 #\a)
(vector 17 0)
(vector 17 33)
(define koko (vector 5 5/7))
koko
(define koko (vector 3 #\x52))
koko
(define truer #t)
(vector 6 truer)
(define checker (lambda (x y ) (vector x y)))
(define result (checker 10 truer))
result 
(vector? result)
(define result (checker 0 truer))
result
(vector? result)
(vector-length result)